name: Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    outputs:
      artifact-name: windows-dist

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run dist:win

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
          name: windows-dist
          path: dist/flyffu-launcher-*-setup.exe

  build-macos:
    name: Build Mac DMG
    runs-on: macos-latest
    outputs:
      artifact-name: macos-dist

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run dist:mac

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dist
          path: dist/flyffu-launcher-*.dmg
  upload-assets:
    name: Upload Assets to Tag
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos]

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: dist/

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-dist
          path: dist/

      - run: ls -R dist

      - name: Attach assets to tag (as draft)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/**
          draft: true
          generate_release_notes: false